//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5420
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CQRS.Messages.Events
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EventBase", Namespace="http://tempuri.org/EventDefinitions.xsd")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CQRS.Messages.Events.ElectionAmountChangedEvent))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CQRS.Messages.Events.ElectionMadeEvent))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CQRS.Messages.Events.HsaElectionMadeEvent))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CQRS.Messages.Events.ElectionTerminatedEvent))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CQRS.Messages.Events.NewBenefitDefinedEvent))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CQRS.Messages.Events.BenefitAssignedToYearEvent))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CQRS.Messages.Events.NewPlanYearAssignedEvent))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CQRS.Messages.Events.NewPlanDefinedEvent))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CQRS.Messages.Events.ClaimRequestSubmittedEvent))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CQRS.Messages.Events.ClaimRequestAutoSubstantiatedEvent))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CQRS.Messages.Events.ClaimRequestCreatedPendingVerificationEvent))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CQRS.Messages.Events.CardUseVerifiedEvent))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CQRS.Messages.Events.ClaimRequestRejectedEvent))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CQRS.Messages.Events.ClaimDisbursedEvent))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CQRS.Messages.Events.ClaimNotDisbursedEvent))]
    public partial class EventBase : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int VersionField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Version
        {
            get
            {
                return this.VersionField;
            }
            set
            {
                this.VersionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ElectionAmountChangedEvent", Namespace="http://tempuri.org/EventDefinitions.xsd")]
    public partial class ElectionAmountChangedEvent : CQRS.Messages.Events.EventBase
    {
        
        private string ElectionIdField;
        
        private string QualifyingEventField;
        
        private decimal NewElectionAmountField;
        
        private decimal NewPerPayPeriodAmountField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string ElectionId
        {
            get
            {
                return this.ElectionIdField;
            }
            set
            {
                this.ElectionIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string QualifyingEvent
        {
            get
            {
                return this.QualifyingEventField;
            }
            set
            {
                this.QualifyingEventField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public decimal NewElectionAmount
        {
            get
            {
                return this.NewElectionAmountField;
            }
            set
            {
                this.NewElectionAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public decimal NewPerPayPeriodAmount
        {
            get
            {
                return this.NewPerPayPeriodAmountField;
            }
            set
            {
                this.NewPerPayPeriodAmountField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ElectionMadeEvent", Namespace="http://tempuri.org/EventDefinitions.xsd")]
    public partial class ElectionMadeEvent : CQRS.Messages.Events.EventBase
    {
        
        private string IdField;
        
        private string AdministratorCodeField;
        
        private string CompanyCodeField;
        
        private string ParticipantIdField;
        
        private string ElectionReasonField;
        
        private decimal ElectionAmountField;
        
        private decimal PerPayPeriodAmountField;
        
        private string PlanYearBenefitIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=1)]
        public string AdministratorCode
        {
            get
            {
                return this.AdministratorCodeField;
            }
            set
            {
                this.AdministratorCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=2)]
        public string CompanyCode
        {
            get
            {
                return this.CompanyCodeField;
            }
            set
            {
                this.CompanyCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=3)]
        public string ParticipantId
        {
            get
            {
                return this.ParticipantIdField;
            }
            set
            {
                this.ParticipantIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=4)]
        public string ElectionReason
        {
            get
            {
                return this.ElectionReasonField;
            }
            set
            {
                this.ElectionReasonField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public decimal ElectionAmount
        {
            get
            {
                return this.ElectionAmountField;
            }
            set
            {
                this.ElectionAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public decimal PerPayPeriodAmount
        {
            get
            {
                return this.PerPayPeriodAmountField;
            }
            set
            {
                this.PerPayPeriodAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=7)]
        public string PlanYearBenefitId
        {
            get
            {
                return this.PlanYearBenefitIdField;
            }
            set
            {
                this.PlanYearBenefitIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HsaElectionMadeEvent", Namespace="http://tempuri.org/EventDefinitions.xsd")]
    public partial class HsaElectionMadeEvent : CQRS.Messages.Events.EventBase
    {
        
        private string IdField;
        
        private string AdministratorCodeField;
        
        private string CompanyCodeField;
        
        private string ParticipantIdField;
        
        private int PlanCodeField;
        
        private string BenefitCodeField;
        
        private string ElectionReasonField;
        
        private decimal ElectionAmountField;
        
        private decimal PerPayPeriodAmountField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=1)]
        public string AdministratorCode
        {
            get
            {
                return this.AdministratorCodeField;
            }
            set
            {
                this.AdministratorCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=2)]
        public string CompanyCode
        {
            get
            {
                return this.CompanyCodeField;
            }
            set
            {
                this.CompanyCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=3)]
        public string ParticipantId
        {
            get
            {
                return this.ParticipantIdField;
            }
            set
            {
                this.ParticipantIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int PlanCode
        {
            get
            {
                return this.PlanCodeField;
            }
            set
            {
                this.PlanCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=5)]
        public string BenefitCode
        {
            get
            {
                return this.BenefitCodeField;
            }
            set
            {
                this.BenefitCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=6)]
        public string ElectionReason
        {
            get
            {
                return this.ElectionReasonField;
            }
            set
            {
                this.ElectionReasonField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public decimal ElectionAmount
        {
            get
            {
                return this.ElectionAmountField;
            }
            set
            {
                this.ElectionAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public decimal PerPayPeriodAmount
        {
            get
            {
                return this.PerPayPeriodAmountField;
            }
            set
            {
                this.PerPayPeriodAmountField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ElectionTerminatedEvent", Namespace="http://tempuri.org/EventDefinitions.xsd")]
    public partial class ElectionTerminatedEvent : CQRS.Messages.Events.EventBase
    {
        
        private string ElectionIdField;
        
        private System.DateTime TerminatedDateField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string ElectionId
        {
            get
            {
                return this.ElectionIdField;
            }
            set
            {
                this.ElectionIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime TerminatedDate
        {
            get
            {
                return this.TerminatedDateField;
            }
            set
            {
                this.TerminatedDateField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NewBenefitDefinedEvent", Namespace="http://tempuri.org/EventDefinitions.xsd")]
    public partial class NewBenefitDefinedEvent : CQRS.Messages.Events.EventBase
    {
        
        private string BenefitIdField;
        
        private string PlanIdField;
        
        private string CompanyIdField;
        
        private string BenefitTypeField;
        
        private string BenefitDescriptionField;
        
        private bool HasMaxElectionAmountField;
        
        private decimal MaxElectionAmountField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string BenefitId
        {
            get
            {
                return this.BenefitIdField;
            }
            set
            {
                this.BenefitIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string PlanId
        {
            get
            {
                return this.PlanIdField;
            }
            set
            {
                this.PlanIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=2)]
        public string CompanyId
        {
            get
            {
                return this.CompanyIdField;
            }
            set
            {
                this.CompanyIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=3)]
        public string BenefitType
        {
            get
            {
                return this.BenefitTypeField;
            }
            set
            {
                this.BenefitTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=4)]
        public string BenefitDescription
        {
            get
            {
                return this.BenefitDescriptionField;
            }
            set
            {
                this.BenefitDescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public bool HasMaxElectionAmount
        {
            get
            {
                return this.HasMaxElectionAmountField;
            }
            set
            {
                this.HasMaxElectionAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public decimal MaxElectionAmount
        {
            get
            {
                return this.MaxElectionAmountField;
            }
            set
            {
                this.MaxElectionAmountField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BenefitAssignedToYearEvent", Namespace="http://tempuri.org/EventDefinitions.xsd")]
    public partial class BenefitAssignedToYearEvent : CQRS.Messages.Events.EventBase
    {
        
        private string BenefitIdField;
        
        private int PlanYearField;
        
        private bool HasMaxAnnualAmountField;
        
        private decimal MaxAnnualAmountField;
        
        private System.DateTime StartDateField;
        
        private string PlanIdField;
        
        private string CompanyIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string BenefitId
        {
            get
            {
                return this.BenefitIdField;
            }
            set
            {
                this.BenefitIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int PlanYear
        {
            get
            {
                return this.PlanYearField;
            }
            set
            {
                this.PlanYearField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public bool HasMaxAnnualAmount
        {
            get
            {
                return this.HasMaxAnnualAmountField;
            }
            set
            {
                this.HasMaxAnnualAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public decimal MaxAnnualAmount
        {
            get
            {
                return this.MaxAnnualAmountField;
            }
            set
            {
                this.MaxAnnualAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.DateTime StartDate
        {
            get
            {
                return this.StartDateField;
            }
            set
            {
                this.StartDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=5)]
        public string PlanId
        {
            get
            {
                return this.PlanIdField;
            }
            set
            {
                this.PlanIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=6)]
        public string CompanyId
        {
            get
            {
                return this.CompanyIdField;
            }
            set
            {
                this.CompanyIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NewPlanYearAssignedEvent", Namespace="http://tempuri.org/EventDefinitions.xsd")]
    public partial class NewPlanYearAssignedEvent : CQRS.Messages.Events.EventBase
    {
        
        private string PlanIdField;
        
        private string CompanyIdField;
        
        private string PlanYearIdField;
        
        private int YearField;
        
        private string NameField;
        
        private System.DateTime StartsField;
        
        private System.DateTime EndsField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string PlanId
        {
            get
            {
                return this.PlanIdField;
            }
            set
            {
                this.PlanIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=1)]
        public string CompanyId
        {
            get
            {
                return this.CompanyIdField;
            }
            set
            {
                this.CompanyIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=2)]
        public string PlanYearId
        {
            get
            {
                return this.PlanYearIdField;
            }
            set
            {
                this.PlanYearIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int Year
        {
            get
            {
                return this.YearField;
            }
            set
            {
                this.YearField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=4)]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.DateTime Starts
        {
            get
            {
                return this.StartsField;
            }
            set
            {
                this.StartsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public System.DateTime Ends
        {
            get
            {
                return this.EndsField;
            }
            set
            {
                this.EndsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NewPlanDefinedEvent", Namespace="http://tempuri.org/EventDefinitions.xsd")]
    public partial class NewPlanDefinedEvent : CQRS.Messages.Events.EventBase
    {
        
        private string PlanIdField;
        
        private string CompanyIdField;
        
        private string PlanTypeField;
        
        private string NameField;
        
        private string DescriptionField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string PlanId
        {
            get
            {
                return this.PlanIdField;
            }
            set
            {
                this.PlanIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=1)]
        public string CompanyId
        {
            get
            {
                return this.CompanyIdField;
            }
            set
            {
                this.CompanyIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=2)]
        public string PlanType
        {
            get
            {
                return this.PlanTypeField;
            }
            set
            {
                this.PlanTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=3)]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=4)]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClaimRequestSubmittedEvent", Namespace="http://tempuri.org/EventDefinitions.xsd")]
    public partial class ClaimRequestSubmittedEvent : CQRS.Messages.Events.EventBase
    {
        
        private string ClaimRequestIdField;
        
        private string CompanyIdField;
        
        private string ParticipantIdField;
        
        private System.DateTime DateOfTransactionField;
        
        private string ProviderNameField;
        
        private string ClaimTypeField;
        
        private decimal AmountField;
        
        private string SourceField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string ClaimRequestId
        {
            get
            {
                return this.ClaimRequestIdField;
            }
            set
            {
                this.ClaimRequestIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string CompanyId
        {
            get
            {
                return this.CompanyIdField;
            }
            set
            {
                this.CompanyIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string ParticipantId
        {
            get
            {
                return this.ParticipantIdField;
            }
            set
            {
                this.ParticipantIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.DateTime DateOfTransaction
        {
            get
            {
                return this.DateOfTransactionField;
            }
            set
            {
                this.DateOfTransactionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=4)]
        public string ProviderName
        {
            get
            {
                return this.ProviderNameField;
            }
            set
            {
                this.ProviderNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=5)]
        public string ClaimType
        {
            get
            {
                return this.ClaimTypeField;
            }
            set
            {
                this.ClaimTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public decimal Amount
        {
            get
            {
                return this.AmountField;
            }
            set
            {
                this.AmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=7)]
        public string Source
        {
            get
            {
                return this.SourceField;
            }
            set
            {
                this.SourceField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClaimRequestAutoSubstantiatedEvent", Namespace="http://tempuri.org/EventDefinitions.xsd")]
    public partial class ClaimRequestAutoSubstantiatedEvent : CQRS.Messages.Events.EventBase
    {
        
        private string ClaimRequestIdField;
        
        private string CompanyIdField;
        
        private string ParticipantIdField;
        
        private System.DateTime DateOfTransactionField;
        
        private string ProviderNameField;
        
        private string ClaimTypeField;
        
        private decimal AmountField;
        
        private string SourceField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string ClaimRequestId
        {
            get
            {
                return this.ClaimRequestIdField;
            }
            set
            {
                this.ClaimRequestIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string CompanyId
        {
            get
            {
                return this.CompanyIdField;
            }
            set
            {
                this.CompanyIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string ParticipantId
        {
            get
            {
                return this.ParticipantIdField;
            }
            set
            {
                this.ParticipantIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.DateTime DateOfTransaction
        {
            get
            {
                return this.DateOfTransactionField;
            }
            set
            {
                this.DateOfTransactionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=4)]
        public string ProviderName
        {
            get
            {
                return this.ProviderNameField;
            }
            set
            {
                this.ProviderNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=5)]
        public string ClaimType
        {
            get
            {
                return this.ClaimTypeField;
            }
            set
            {
                this.ClaimTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public decimal Amount
        {
            get
            {
                return this.AmountField;
            }
            set
            {
                this.AmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=7)]
        public string Source
        {
            get
            {
                return this.SourceField;
            }
            set
            {
                this.SourceField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClaimRequestCreatedPendingVerificationEvent", Namespace="http://tempuri.org/EventDefinitions.xsd")]
    public partial class ClaimRequestCreatedPendingVerificationEvent : CQRS.Messages.Events.EventBase
    {
        
        private string ClaimRequestIdField;
        
        private string CompanyIdField;
        
        private string ParticipantIdField;
        
        private System.DateTime DateOfTransactionField;
        
        private string ProviderNameField;
        
        private string ClaimTypeField;
        
        private decimal AmountField;
        
        private string ReasonField;
        
        private string SourceField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string ClaimRequestId
        {
            get
            {
                return this.ClaimRequestIdField;
            }
            set
            {
                this.ClaimRequestIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string CompanyId
        {
            get
            {
                return this.CompanyIdField;
            }
            set
            {
                this.CompanyIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string ParticipantId
        {
            get
            {
                return this.ParticipantIdField;
            }
            set
            {
                this.ParticipantIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.DateTime DateOfTransaction
        {
            get
            {
                return this.DateOfTransactionField;
            }
            set
            {
                this.DateOfTransactionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=4)]
        public string ProviderName
        {
            get
            {
                return this.ProviderNameField;
            }
            set
            {
                this.ProviderNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=5)]
        public string ClaimType
        {
            get
            {
                return this.ClaimTypeField;
            }
            set
            {
                this.ClaimTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public decimal Amount
        {
            get
            {
                return this.AmountField;
            }
            set
            {
                this.AmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=7)]
        public string Reason
        {
            get
            {
                return this.ReasonField;
            }
            set
            {
                this.ReasonField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=8)]
        public string Source
        {
            get
            {
                return this.SourceField;
            }
            set
            {
                this.SourceField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CardUseVerifiedEvent", Namespace="http://tempuri.org/EventDefinitions.xsd")]
    public partial class CardUseVerifiedEvent : CQRS.Messages.Events.EventBase
    {
        
        private string ClaimRequestIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string ClaimRequestId
        {
            get
            {
                return this.ClaimRequestIdField;
            }
            set
            {
                this.ClaimRequestIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClaimRequestRejectedEvent", Namespace="http://tempuri.org/EventDefinitions.xsd")]
    public partial class ClaimRequestRejectedEvent : CQRS.Messages.Events.EventBase
    {
        
        private string ClaimRequestIdField;
        
        private string RejectReasonField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string ClaimRequestId
        {
            get
            {
                return this.ClaimRequestIdField;
            }
            set
            {
                this.ClaimRequestIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string RejectReason
        {
            get
            {
                return this.RejectReasonField;
            }
            set
            {
                this.RejectReasonField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClaimDisbursedEvent", Namespace="http://tempuri.org/EventDefinitions.xsd")]
    public partial class ClaimDisbursedEvent : CQRS.Messages.Events.EventBase
    {
        
        private string ClaimIdField;
        
        private string ElectionIdField;
        
        private decimal ClaimAmountField;
        
        private decimal DisbursementAmountField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string ClaimId
        {
            get
            {
                return this.ClaimIdField;
            }
            set
            {
                this.ClaimIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string ElectionId
        {
            get
            {
                return this.ElectionIdField;
            }
            set
            {
                this.ElectionIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public decimal ClaimAmount
        {
            get
            {
                return this.ClaimAmountField;
            }
            set
            {
                this.ClaimAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public decimal DisbursementAmount
        {
            get
            {
                return this.DisbursementAmountField;
            }
            set
            {
                this.DisbursementAmountField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClaimNotDisbursedEvent", Namespace="http://tempuri.org/EventDefinitions.xsd")]
    public partial class ClaimNotDisbursedEvent : CQRS.Messages.Events.EventBase
    {
        
        private string ClaimIdField;
        
        private decimal ClaimAmountField;
        
        private string ClaimTypeField;
        
        private string ReasonField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string ClaimId
        {
            get
            {
                return this.ClaimIdField;
            }
            set
            {
                this.ClaimIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public decimal ClaimAmount
        {
            get
            {
                return this.ClaimAmountField;
            }
            set
            {
                this.ClaimAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=2)]
        public string ClaimType
        {
            get
            {
                return this.ClaimTypeField;
            }
            set
            {
                this.ClaimTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=3)]
        public string Reason
        {
            get
            {
                return this.ReasonField;
            }
            set
            {
                this.ReasonField = value;
            }
        }
    }
}
