//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5420
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;

namespace MHM.WinFlexOne.CQRS.Dtos
{
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClaimStateEnum", Namespace="http://tempuri.org/DtoDefinitions.xsd")]
    public enum ClaimStateEnum : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PendingSubstantiation = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Substantiated = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Rejected = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Paid = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ElectionDto", Namespace="http://tempuri.org/DtoDefinitions.xsd")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MHM.WinFlexOne.CQRS.Dtos.ClaimStateEnum))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MHM.WinFlexOne.CQRS.Dtos.ElectionBalanceDto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MHM.WinFlexOne.CQRS.Dtos.ParticipantDto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MHM.WinFlexOne.CQRS.Dtos.PlanYearBenefitDto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MHM.WinFlexOne.CQRS.Dtos.BenefitDto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MHM.WinFlexOne.CQRS.Dtos.CompanyDto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MHM.WinFlexOne.CQRS.Dtos.PlanDto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MHM.WinFlexOne.CQRS.Dtos.PlanYearDto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MHM.WinFlexOne.CQRS.Dtos.ClaimDto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MHM.WinFlexOne.CQRS.Dtos.CopayInfo))]
    public partial class ElectionDto : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string IdField;
        
        private object CompanyIdField;
        
        private object CompanyNameField;
        
        private string ParticipantIdField;
        
        private string PlanCodeField;
        
        private int PlanYearField;
        
        private string BenefitCodeField;
        
        private string PlanYearBenefitIdField;
        
        private string PlanYearBenefitDescField;
        
        private string BenefitTypeField;
        
        private bool IsTerminatedField;
        
        private System.DateTime TerminationDateField;
        
        private string QualifyingEventField;
        
        private decimal ElectionAmountField;
        
        private decimal BalanceField;
        
        private decimal PerPayPeriodAmountField;
        
        private int VersionField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=1)]
        public object CompanyId
        {
            get
            {
                return this.CompanyIdField;
            }
            set
            {
                this.CompanyIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=2)]
        public object CompanyName
        {
            get
            {
                return this.CompanyNameField;
            }
            set
            {
                this.CompanyNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=3)]
        public string ParticipantId
        {
            get
            {
                return this.ParticipantIdField;
            }
            set
            {
                this.ParticipantIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=4)]
        public string PlanCode
        {
            get
            {
                return this.PlanCodeField;
            }
            set
            {
                this.PlanCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int PlanYear
        {
            get
            {
                return this.PlanYearField;
            }
            set
            {
                this.PlanYearField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=6)]
        public string BenefitCode
        {
            get
            {
                return this.BenefitCodeField;
            }
            set
            {
                this.BenefitCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=7)]
        public string PlanYearBenefitId
        {
            get
            {
                return this.PlanYearBenefitIdField;
            }
            set
            {
                this.PlanYearBenefitIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=8)]
        public string PlanYearBenefitDesc
        {
            get
            {
                return this.PlanYearBenefitDescField;
            }
            set
            {
                this.PlanYearBenefitDescField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=9)]
        public string BenefitType
        {
            get
            {
                return this.BenefitTypeField;
            }
            set
            {
                this.BenefitTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public bool IsTerminated
        {
            get
            {
                return this.IsTerminatedField;
            }
            set
            {
                this.IsTerminatedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public System.DateTime TerminationDate
        {
            get
            {
                return this.TerminationDateField;
            }
            set
            {
                this.TerminationDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=12)]
        public string QualifyingEvent
        {
            get
            {
                return this.QualifyingEventField;
            }
            set
            {
                this.QualifyingEventField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=13)]
        public decimal ElectionAmount
        {
            get
            {
                return this.ElectionAmountField;
            }
            set
            {
                this.ElectionAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=14)]
        public decimal Balance
        {
            get
            {
                return this.BalanceField;
            }
            set
            {
                this.BalanceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=15)]
        public decimal PerPayPeriodAmount
        {
            get
            {
                return this.PerPayPeriodAmountField;
            }
            set
            {
                this.PerPayPeriodAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=16)]
        public int Version
        {
            get
            {
                return this.VersionField;
            }
            set
            {
                this.VersionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ElectionBalanceDto", Namespace="http://tempuri.org/DtoDefinitions.xsd")]
    public partial class ElectionBalanceDto : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string IdField;
        
        private string ElectionIdField;
        
        private string ParticipantIdField;
        
        private string ElectionDescriptionField;
        
        private decimal ElectionAmountField;
        
        private decimal BalanceRemainingField;
        
        private List<string> ClaimsField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=1)]
        public string ElectionId
        {
            get
            {
                return this.ElectionIdField;
            }
            set
            {
                this.ElectionIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=2)]
        public string ParticipantId
        {
            get
            {
                return this.ParticipantIdField;
            }
            set
            {
                this.ParticipantIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=3)]
        public string ElectionDescription
        {
            get
            {
                return this.ElectionDescriptionField;
            }
            set
            {
                this.ElectionDescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public decimal ElectionAmount
        {
            get
            {
                return this.ElectionAmountField;
            }
            set
            {
                this.ElectionAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public decimal BalanceRemaining
        {
            get
            {
                return this.BalanceRemainingField;
            }
            set
            {
                this.BalanceRemainingField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=6)]
        public List<string> Claims
        {
            get
            {
                return this.ClaimsField;
            }
            set
            {
                this.ClaimsField = value;
            }
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
        [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ElectionBalanceDto.ClaimsType", Namespace="http://tempuri.org/DtoDefinitions.xsd", ItemName="ClaimId")]
        public class ClaimsType : System.Collections.Generic.List<string>
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ParticipantDto", Namespace="http://tempuri.org/DtoDefinitions.xsd")]
    public partial class ParticipantDto : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string FirstNameField;
        
        private string LastNameField;
        
        private string EmployerField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string FirstName
        {
            get
            {
                return this.FirstNameField;
            }
            set
            {
                this.FirstNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string LastName
        {
            get
            {
                return this.LastNameField;
            }
            set
            {
                this.LastNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=2)]
        public string Employer
        {
            get
            {
                return this.EmployerField;
            }
            set
            {
                this.EmployerField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PlanYearBenefitDto", Namespace="http://tempuri.org/DtoDefinitions.xsd")]
    public partial class PlanYearBenefitDto : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string IdField;
        
        private string PlanIdField;
        
        private string BenefitIdField;
        
        private string CompanyIdField;
        
        private string NameField;
        
        private int PlanYearField;
        
        private bool HasAnnualLimitField;
        
        private decimal AnnualLimitField;
        
        private System.DateTime StartDateField;
        
        private System.DateTime EndDateField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string PlanId
        {
            get
            {
                return this.PlanIdField;
            }
            set
            {
                this.PlanIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=2)]
        public string BenefitId
        {
            get
            {
                return this.BenefitIdField;
            }
            set
            {
                this.BenefitIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=3)]
        public string CompanyId
        {
            get
            {
                return this.CompanyIdField;
            }
            set
            {
                this.CompanyIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=4)]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int PlanYear
        {
            get
            {
                return this.PlanYearField;
            }
            set
            {
                this.PlanYearField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public bool HasAnnualLimit
        {
            get
            {
                return this.HasAnnualLimitField;
            }
            set
            {
                this.HasAnnualLimitField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public decimal AnnualLimit
        {
            get
            {
                return this.AnnualLimitField;
            }
            set
            {
                this.AnnualLimitField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public System.DateTime StartDate
        {
            get
            {
                return this.StartDateField;
            }
            set
            {
                this.StartDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public System.DateTime EndDate
        {
            get
            {
                return this.EndDateField;
            }
            set
            {
                this.EndDateField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BenefitDto", Namespace="http://tempuri.org/DtoDefinitions.xsd")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MHM.WinFlexOne.CQRS.Dtos.ClaimStateEnum))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MHM.WinFlexOne.CQRS.Dtos.ElectionDto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MHM.WinFlexOne.CQRS.Dtos.ElectionBalanceDto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MHM.WinFlexOne.CQRS.Dtos.ParticipantDto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MHM.WinFlexOne.CQRS.Dtos.PlanYearBenefitDto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MHM.WinFlexOne.CQRS.Dtos.CompanyDto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MHM.WinFlexOne.CQRS.Dtos.PlanDto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MHM.WinFlexOne.CQRS.Dtos.PlanYearDto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MHM.WinFlexOne.CQRS.Dtos.ClaimDto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MHM.WinFlexOne.CQRS.Dtos.CopayInfo))]
    public partial class BenefitDto : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string IdField;
        
        private string CompanyIdField;
        
        private string PlanIdField;
        
        private object PlanYearIdField;
        
        private string BenefitTypeField;
        
        private string DescriptionField;
        
        private bool HasMaxElectionAmountField;
        
        private decimal MaxElectionAmountField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=1)]
        public string CompanyId
        {
            get
            {
                return this.CompanyIdField;
            }
            set
            {
                this.CompanyIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=2)]
        public string PlanId
        {
            get
            {
                return this.PlanIdField;
            }
            set
            {
                this.PlanIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=3)]
        public object PlanYearId
        {
            get
            {
                return this.PlanYearIdField;
            }
            set
            {
                this.PlanYearIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=4)]
        public string BenefitType
        {
            get
            {
                return this.BenefitTypeField;
            }
            set
            {
                this.BenefitTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=5)]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public bool HasMaxElectionAmount
        {
            get
            {
                return this.HasMaxElectionAmountField;
            }
            set
            {
                this.HasMaxElectionAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public decimal MaxElectionAmount
        {
            get
            {
                return this.MaxElectionAmountField;
            }
            set
            {
                this.MaxElectionAmountField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompanyDto", Namespace="http://tempuri.org/DtoDefinitions.xsd")]
    public partial class CompanyDto : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string IdField;
        
        private string AdmCodeField;
        
        private string CompanyNameField;
        
        private MHM.WinFlexOne.CQRS.Dtos.CompanyDto.PlansType PlansField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=1)]
        public string AdmCode
        {
            get
            {
                return this.AdmCodeField;
            }
            set
            {
                this.AdmCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=2)]
        public string CompanyName
        {
            get
            {
                return this.CompanyNameField;
            }
            set
            {
                this.CompanyNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=3)]
        public MHM.WinFlexOne.CQRS.Dtos.CompanyDto.PlansType Plans
        {
            get
            {
                return this.PlansField;
            }
            set
            {
                this.PlansField = value;
            }
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
        [System.Runtime.Serialization.CollectionDataContractAttribute(Name="CompanyDto.PlansType", Namespace="http://tempuri.org/DtoDefinitions.xsd", ItemName="PlanId")]
        public class PlansType : System.Collections.Generic.List<string>
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PlanDto", Namespace="http://tempuri.org/DtoDefinitions.xsd")]
    public partial class PlanDto : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string IdField;
        
        private string PlanTypeField;
        
        private string CompanyIdField;
        
        private string NameField;
        
        private string DescriptionField;
        
        //private MHM.WinFlexOne.CQRS.Dtos.PlanDto.PlanYearsType PlanYearsField;
        private List<string> PlanYearsField;
        
        //private MHM.WinFlexOne.CQRS.Dtos.PlanDto.CopaysType CopaysField;
        private List<CopayInfo> CopaysField; 
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string PlanType
        {
            get
            {
                return this.PlanTypeField;
            }
            set
            {
                this.PlanTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=2)]
        public string CompanyId
        {
            get
            {
                return this.CompanyIdField;
            }
            set
            {
                this.CompanyIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=3)]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=4)]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=5)]
        public List<string> PlanYears
        {
            get
            {
                return this.PlanYearsField;
            }
            set
            {
                this.PlanYearsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=6)]
        public List<CopayInfo> Copays
        {
            get
            {
                return this.CopaysField;
            }
            set
            {
                this.CopaysField = value;
            }
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
        [System.Runtime.Serialization.CollectionDataContractAttribute(Name="PlanDto.PlanYearsType", Namespace="http://tempuri.org/DtoDefinitions.xsd", ItemName="PlanYearId")]
        public class PlanYearsType : System.Collections.Generic.List<string>
        {
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
        [System.Runtime.Serialization.CollectionDataContractAttribute(Name="PlanDto.CopaysType", Namespace="http://tempuri.org/DtoDefinitions.xsd", ItemName="CopayInfo")]
        public class CopaysType : System.Collections.Generic.List<MHM.WinFlexOne.CQRS.Dtos.CopayInfo>
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PlanYearDto", Namespace="http://tempuri.org/DtoDefinitions.xsd")]
    public partial class PlanYearDto : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string IdField;
        
        private string PlanIdField;
        
        private string CompanyIdField;
        
        private string NameField;
        
        private int YearField;
        
        private System.DateTime StartsField;
        
        private System.DateTime EndsField;
        
        private List<string> BenefitsField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string PlanId
        {
            get
            {
                return this.PlanIdField;
            }
            set
            {
                this.PlanIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=2)]
        public string CompanyId
        {
            get
            {
                return this.CompanyIdField;
            }
            set
            {
                this.CompanyIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=3)]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int Year
        {
            get
            {
                return this.YearField;
            }
            set
            {
                this.YearField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.DateTime Starts
        {
            get
            {
                return this.StartsField;
            }
            set
            {
                this.StartsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public System.DateTime Ends
        {
            get
            {
                return this.EndsField;
            }
            set
            {
                this.EndsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=7)]
        public List<string> Benefits
        {
            get
            {
                return this.BenefitsField;
            }
            set
            {
                this.BenefitsField = value;
            }
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
        [System.Runtime.Serialization.CollectionDataContractAttribute(Name="PlanYearDto.BenefitsType", Namespace="http://tempuri.org/DtoDefinitions.xsd", ItemName="BenefitId")]
        public class BenefitsType : System.Collections.Generic.List<string>
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClaimDto", Namespace="http://tempuri.org/DtoDefinitions.xsd")]
    public partial class ClaimDto : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string IdField;
        
        private string ParticipantIdField;
        
        private System.DateTime ServiceDateField;
        
        private string ProviderField;
        
        private string ClaimTypeField;
        
        private MHM.WinFlexOne.CQRS.Dtos.ClaimStateEnum ClaimStateField;
        
        private string SourceField;
        
        private string ElectionIdField;
        
        private decimal ClaimAmountField;
        
        private decimal AmountPaidField;
        
        private string RejectReasonField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string ParticipantId
        {
            get
            {
                return this.ParticipantIdField;
            }
            set
            {
                this.ParticipantIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime ServiceDate
        {
            get
            {
                return this.ServiceDateField;
            }
            set
            {
                this.ServiceDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=3)]
        public string Provider
        {
            get
            {
                return this.ProviderField;
            }
            set
            {
                this.ProviderField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=4)]
        public string ClaimType
        {
            get
            {
                return this.ClaimTypeField;
            }
            set
            {
                this.ClaimTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public MHM.WinFlexOne.CQRS.Dtos.ClaimStateEnum ClaimState
        {
            get
            {
                return this.ClaimStateField;
            }
            set
            {
                this.ClaimStateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=6)]
        public string Source
        {
            get
            {
                return this.SourceField;
            }
            set
            {
                this.SourceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=7)]
        public string ElectionId
        {
            get
            {
                return this.ElectionIdField;
            }
            set
            {
                this.ElectionIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public decimal ClaimAmount
        {
            get
            {
                return this.ClaimAmountField;
            }
            set
            {
                this.ClaimAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public decimal AmountPaid
        {
            get
            {
                return this.AmountPaidField;
            }
            set
            {
                this.AmountPaidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=10)]
        public string RejectReason
        {
            get
            {
                return this.RejectReasonField;
            }
            set
            {
                this.RejectReasonField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CopayInfo", Namespace="http://tempuri.org/DtoDefinitions.xsd")]
    public partial class CopayInfo : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string CompanyIdField;
        
        private string CompanyNameField;
        
        private string PlanIdField;
        
        private string PlanNameField;
        
        private string ClaimTypeField;
        
        private decimal CopayAmountField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string CompanyId
        {
            get
            {
                return this.CompanyIdField;
            }
            set
            {
                this.CompanyIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string CompanyName
        {
            get
            {
                return this.CompanyNameField;
            }
            set
            {
                this.CompanyNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string PlanId
        {
            get
            {
                return this.PlanIdField;
            }
            set
            {
                this.PlanIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string PlanName
        {
            get
            {
                return this.PlanNameField;
            }
            set
            {
                this.PlanNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=4)]
        public string ClaimType
        {
            get
            {
                return this.ClaimTypeField;
            }
            set
            {
                this.ClaimTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public decimal CopayAmount
        {
            get
            {
                return this.CopayAmountField;
            }
            set
            {
                this.CopayAmountField = value;
            }
        }
    }
}
