//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5456
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MHM.WinFlexOne.CQRS.Commands
{
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CommandStatusEnum", Namespace="http://tempuri.org/CommandDefinitions.xsd")]
    public enum CommandStatusEnum : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Succeeded = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Failed = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CommandResponse", Namespace="http://tempuri.org/CommandDefinitions.xsd")]
    public partial class CommandResponse : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string CommandIdField;
        
        private MHM.WinFlexOne.CQRS.Commands.CommandStatusEnum CommandStatusField;
        
        private bool ContainsExceptionField;
        
        private string ExceptionDetailField;
        
        private string MessageField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string CommandId
        {
            get
            {
                return this.CommandIdField;
            }
            set
            {
                this.CommandIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public MHM.WinFlexOne.CQRS.Commands.CommandStatusEnum CommandStatus
        {
            get
            {
                return this.CommandStatusField;
            }
            set
            {
                this.CommandStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool ContainsException
        {
            get
            {
                return this.ContainsExceptionField;
            }
            set
            {
                this.ContainsExceptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ExceptionDetail
        {
            get
            {
                return this.ExceptionDetailField;
            }
            set
            {
                this.ExceptionDetailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MakeAnElection", Namespace="http://tempuri.org/CommandDefinitions.xsd")]
    public partial class MakeAnElection : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string IdField;
        
        private string AdministratorCodeField;
        
        private string CompanyCodeField;
        
        private string ParticipantIdField;
        
        private string PlanYearBenefitIdField;
        
        private string ElectionReasonField;
        
        private decimal ElectionAmountField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=1)]
        public string AdministratorCode
        {
            get
            {
                return this.AdministratorCodeField;
            }
            set
            {
                this.AdministratorCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=2)]
        public string CompanyCode
        {
            get
            {
                return this.CompanyCodeField;
            }
            set
            {
                this.CompanyCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=3)]
        public string ParticipantId
        {
            get
            {
                return this.ParticipantIdField;
            }
            set
            {
                this.ParticipantIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=4)]
        public string PlanYearBenefitId
        {
            get
            {
                return this.PlanYearBenefitIdField;
            }
            set
            {
                this.PlanYearBenefitIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=5)]
        public string ElectionReason
        {
            get
            {
                return this.ElectionReasonField;
            }
            set
            {
                this.ElectionReasonField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public decimal ElectionAmount
        {
            get
            {
                return this.ElectionAmountField;
            }
            set
            {
                this.ElectionAmountField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MakeHsaElection", Namespace="http://tempuri.org/CommandDefinitions.xsd")]
    public partial class MakeHsaElection : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string IdField;
        
        private string AdministratorCodeField;
        
        private string CompanyCodeField;
        
        private string ParticipantIdField;
        
        private int PlanCodeField;
        
        private string BenefitCodeField;
        
        private string ElectionReasonField;
        
        private decimal ElectionAmountField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=1)]
        public string AdministratorCode
        {
            get
            {
                return this.AdministratorCodeField;
            }
            set
            {
                this.AdministratorCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=2)]
        public string CompanyCode
        {
            get
            {
                return this.CompanyCodeField;
            }
            set
            {
                this.CompanyCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=3)]
        public string ParticipantId
        {
            get
            {
                return this.ParticipantIdField;
            }
            set
            {
                this.ParticipantIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int PlanCode
        {
            get
            {
                return this.PlanCodeField;
            }
            set
            {
                this.PlanCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=5)]
        public string BenefitCode
        {
            get
            {
                return this.BenefitCodeField;
            }
            set
            {
                this.BenefitCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=6)]
        public string ElectionReason
        {
            get
            {
                return this.ElectionReasonField;
            }
            set
            {
                this.ElectionReasonField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public decimal ElectionAmount
        {
            get
            {
                return this.ElectionAmountField;
            }
            set
            {
                this.ElectionAmountField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ChangeElectionAmount", Namespace="http://tempuri.org/CommandDefinitions.xsd")]
    public partial class ChangeElectionAmount : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string ElectionIdField;
        
        private string PlanYearBenefitIdField;
        
        private decimal NewElectionAmountField;
        
        private string QualifyingEventField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string ElectionId
        {
            get
            {
                return this.ElectionIdField;
            }
            set
            {
                this.ElectionIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string PlanYearBenefitId
        {
            get
            {
                return this.PlanYearBenefitIdField;
            }
            set
            {
                this.PlanYearBenefitIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public decimal NewElectionAmount
        {
            get
            {
                return this.NewElectionAmountField;
            }
            set
            {
                this.NewElectionAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=3)]
        public string QualifyingEvent
        {
            get
            {
                return this.QualifyingEventField;
            }
            set
            {
                this.QualifyingEventField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TerminateElection", Namespace="http://tempuri.org/CommandDefinitions.xsd")]
    public partial class TerminateElection : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string ElectionIdField;
        
        private System.DateTime TerminationDateField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string ElectionId
        {
            get
            {
                return this.ElectionIdField;
            }
            set
            {
                this.ElectionIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime TerminationDate
        {
            get
            {
                return this.TerminationDateField;
            }
            set
            {
                this.TerminationDateField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RegisterNewParticipant", Namespace="http://tempuri.org/CommandDefinitions.xsd")]
    public partial class RegisterNewParticipant : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string IdField;
        
        private string AdministratorCodeField;
        
        private string CompanyCodeField;
        
        private string FirstNameField;
        
        private string MiddleInitialField;
        
        private string LastNameField;
        
        private string SsnHashField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=1)]
        public string AdministratorCode
        {
            get
            {
                return this.AdministratorCodeField;
            }
            set
            {
                this.AdministratorCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=2)]
        public string CompanyCode
        {
            get
            {
                return this.CompanyCodeField;
            }
            set
            {
                this.CompanyCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=3)]
        public string FirstName
        {
            get
            {
                return this.FirstNameField;
            }
            set
            {
                this.FirstNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=4)]
        public string MiddleInitial
        {
            get
            {
                return this.MiddleInitialField;
            }
            set
            {
                this.MiddleInitialField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=5)]
        public string LastName
        {
            get
            {
                return this.LastNameField;
            }
            set
            {
                this.LastNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=6)]
        public string SsnHash
        {
            get
            {
                return this.SsnHashField;
            }
            set
            {
                this.SsnHashField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ParticipantSubmitsNewClaim", Namespace="http://tempuri.org/CommandDefinitions.xsd")]
    public partial class ParticipantSubmitsNewClaim : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string IdField;
        
        private string ClaimTypeField;
        
        private decimal ClaimAmountField;
        
        private string ServiceStartDateField;
        
        private string ServiceEndDateField;
        
        private string ServiceProviderField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=1)]
        public string ClaimType
        {
            get
            {
                return this.ClaimTypeField;
            }
            set
            {
                this.ClaimTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public decimal ClaimAmount
        {
            get
            {
                return this.ClaimAmountField;
            }
            set
            {
                this.ClaimAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=3)]
        public string ServiceStartDate
        {
            get
            {
                return this.ServiceStartDateField;
            }
            set
            {
                this.ServiceStartDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=4)]
        public string ServiceEndDate
        {
            get
            {
                return this.ServiceEndDateField;
            }
            set
            {
                this.ServiceEndDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=5)]
        public string ServiceProvider
        {
            get
            {
                return this.ServiceProviderField;
            }
            set
            {
                this.ServiceProviderField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DefineNewBenefit", Namespace="http://tempuri.org/CommandDefinitions.xsd")]
    public partial class DefineNewBenefit : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string BenefitIdField;
        
        private string PlanIdField;
        
        private string CompanyIdField;
        
        private string BenefitTypeField;
        
        private string BenefitDescriptionField;
        
        private bool HasMaxAmountField;
        
        private decimal MaxBenefitAmountField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string BenefitId
        {
            get
            {
                return this.BenefitIdField;
            }
            set
            {
                this.BenefitIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string PlanId
        {
            get
            {
                return this.PlanIdField;
            }
            set
            {
                this.PlanIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=2)]
        public string CompanyId
        {
            get
            {
                return this.CompanyIdField;
            }
            set
            {
                this.CompanyIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=3)]
        public string BenefitType
        {
            get
            {
                return this.BenefitTypeField;
            }
            set
            {
                this.BenefitTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=4)]
        public string BenefitDescription
        {
            get
            {
                return this.BenefitDescriptionField;
            }
            set
            {
                this.BenefitDescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public bool HasMaxAmount
        {
            get
            {
                return this.HasMaxAmountField;
            }
            set
            {
                this.HasMaxAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public decimal MaxBenefitAmount
        {
            get
            {
                return this.MaxBenefitAmountField;
            }
            set
            {
                this.MaxBenefitAmountField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AssignBenefitToYear", Namespace="http://tempuri.org/CommandDefinitions.xsd")]
    public partial class AssignBenefitToYear : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string BenefitIdField;
        
        private string PlanIdField;
        
        private int PlanYearField;
        
        private bool HasMaxAnnualAmountField;
        
        private decimal MaxAnnualAmountField;
        
        private System.DateTime StartDateField;
        
        private string CompanyIdField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string BenefitId
        {
            get
            {
                return this.BenefitIdField;
            }
            set
            {
                this.BenefitIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string PlanId
        {
            get
            {
                return this.PlanIdField;
            }
            set
            {
                this.PlanIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int PlanYear
        {
            get
            {
                return this.PlanYearField;
            }
            set
            {
                this.PlanYearField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public bool HasMaxAnnualAmount
        {
            get
            {
                return this.HasMaxAnnualAmountField;
            }
            set
            {
                this.HasMaxAnnualAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public decimal MaxAnnualAmount
        {
            get
            {
                return this.MaxAnnualAmountField;
            }
            set
            {
                this.MaxAnnualAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.DateTime StartDate
        {
            get
            {
                return this.StartDateField;
            }
            set
            {
                this.StartDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=6)]
        public string CompanyId
        {
            get
            {
                return this.CompanyIdField;
            }
            set
            {
                this.CompanyIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DefineYearForPlan", Namespace="http://tempuri.org/CommandDefinitions.xsd")]
    public partial class DefineYearForPlan : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string PlanIdField;
        
        private string CompanyIdField;
        
        private string PlanYearIdField;
        
        private int YearField;
        
        private string NameField;
        
        private System.DateTime StartsField;
        
        private System.DateTime EndsField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string PlanId
        {
            get
            {
                return this.PlanIdField;
            }
            set
            {
                this.PlanIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=1)]
        public string CompanyId
        {
            get
            {
                return this.CompanyIdField;
            }
            set
            {
                this.CompanyIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=2)]
        public string PlanYearId
        {
            get
            {
                return this.PlanYearIdField;
            }
            set
            {
                this.PlanYearIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int Year
        {
            get
            {
                return this.YearField;
            }
            set
            {
                this.YearField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=4)]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.DateTime Starts
        {
            get
            {
                return this.StartsField;
            }
            set
            {
                this.StartsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public System.DateTime Ends
        {
            get
            {
                return this.EndsField;
            }
            set
            {
                this.EndsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DefineNewPlan", Namespace="http://tempuri.org/CommandDefinitions.xsd")]
    public partial class DefineNewPlan : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string PlanIdField;
        
        private string CompanyIdField;
        
        private string PlanTypeField;
        
        private string NameField;
        
        private string DescriptionField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string PlanId
        {
            get
            {
                return this.PlanIdField;
            }
            set
            {
                this.PlanIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=1)]
        public string CompanyId
        {
            get
            {
                return this.CompanyIdField;
            }
            set
            {
                this.CompanyIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=2)]
        public string PlanType
        {
            get
            {
                return this.PlanTypeField;
            }
            set
            {
                this.PlanTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=3)]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=4)]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SubmitClaimRequest", Namespace="http://tempuri.org/CommandDefinitions.xsd")]
    public partial class SubmitClaimRequest : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string ClaimRequestIdField;
        
        private string CompanyIdField;
        
        private string ParticipantIdField;
        
        private System.DateTime DateOfTransactionField;
        
        private string ProviderNameField;
        
        private string ClaimTypeField;
        
        private decimal AmountField;
        
        private string SourceField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string ClaimRequestId
        {
            get
            {
                return this.ClaimRequestIdField;
            }
            set
            {
                this.ClaimRequestIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string CompanyId
        {
            get
            {
                return this.CompanyIdField;
            }
            set
            {
                this.CompanyIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string ParticipantId
        {
            get
            {
                return this.ParticipantIdField;
            }
            set
            {
                this.ParticipantIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.DateTime DateOfTransaction
        {
            get
            {
                return this.DateOfTransactionField;
            }
            set
            {
                this.DateOfTransactionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=4)]
        public string ProviderName
        {
            get
            {
                return this.ProviderNameField;
            }
            set
            {
                this.ProviderNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=5)]
        public string ClaimType
        {
            get
            {
                return this.ClaimTypeField;
            }
            set
            {
                this.ClaimTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public decimal Amount
        {
            get
            {
                return this.AmountField;
            }
            set
            {
                this.AmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=7)]
        public string Source
        {
            get
            {
                return this.SourceField;
            }
            set
            {
                this.SourceField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RejectClaimRequest", Namespace="http://tempuri.org/CommandDefinitions.xsd")]
    public partial class RejectClaimRequest : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string ClaimRequestIdField;
        
        private string ReasonField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string ClaimRequestId
        {
            get
            {
                return this.ClaimRequestIdField;
            }
            set
            {
                this.ClaimRequestIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string Reason
        {
            get
            {
                return this.ReasonField;
            }
            set
            {
                this.ReasonField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VerifyCardUse", Namespace="http://tempuri.org/CommandDefinitions.xsd")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MHM.WinFlexOne.CQRS.Commands.CommandStatusEnum))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MHM.WinFlexOne.CQRS.Commands.CommandResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MHM.WinFlexOne.CQRS.Commands.MakeAnElection))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MHM.WinFlexOne.CQRS.Commands.MakeHsaElection))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MHM.WinFlexOne.CQRS.Commands.ChangeElectionAmount))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MHM.WinFlexOne.CQRS.Commands.TerminateElection))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MHM.WinFlexOne.CQRS.Commands.RegisterNewParticipant))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MHM.WinFlexOne.CQRS.Commands.ParticipantSubmitsNewClaim))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MHM.WinFlexOne.CQRS.Commands.DefineNewBenefit))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MHM.WinFlexOne.CQRS.Commands.AssignBenefitToYear))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MHM.WinFlexOne.CQRS.Commands.DefineYearForPlan))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MHM.WinFlexOne.CQRS.Commands.DefineNewPlan))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MHM.WinFlexOne.CQRS.Commands.SubmitClaimRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MHM.WinFlexOne.CQRS.Commands.RejectClaimRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MHM.WinFlexOne.CQRS.Commands.StartTimeout))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MHM.WinFlexOne.CQRS.Commands.DisburseClaim))]
    public partial class VerifyCardUse : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string ClaimRequestIdField;
        
        private object CommentsField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string ClaimRequestId
        {
            get
            {
                return this.ClaimRequestIdField;
            }
            set
            {
                this.ClaimRequestIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public object Comments
        {
            get
            {
                return this.CommentsField;
            }
            set
            {
                this.CommentsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StartTimeout", Namespace="http://tempuri.org/CommandDefinitions.xsd")]
    public partial class StartTimeout : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string CorrelationIdField;
        
        private int ElapsesInMSField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string CorrelationId
        {
            get
            {
                return this.CorrelationIdField;
            }
            set
            {
                this.CorrelationIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ElapsesInMS
        {
            get
            {
                return this.ElapsesInMSField;
            }
            set
            {
                this.ElapsesInMSField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DisburseClaim", Namespace="http://tempuri.org/CommandDefinitions.xsd")]
    public partial class DisburseClaim : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string ClaimIdField;
        
        private string ParticipantIdField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string ClaimId
        {
            get
            {
                return this.ClaimIdField;
            }
            set
            {
                this.ClaimIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string ParticipantId
        {
            get
            {
                return this.ParticipantIdField;
            }
            set
            {
                this.ParticipantIdField = value;
            }
        }
    }
}
